version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env.local
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres:
